### ISSUE TITLE
Wording issues in installer- UI/UX issues

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#10]
Unclear when to set up ssh key/if it is necessary first or last or at all

Some steps are put in the window title bar (at the top of the window), this confuses me on where to look for the instructions. The choose catking dir step does this.

Some instructions are too verbose, reduce wordiness. (ex. Are you currently installing on the robot computer? Vs. Are you on the robot computer?)

Should be some help box for when I dont know what something means, or some extra full document with explanation of each step. (ex. What are custom IP configs and why does it matter?)

**Comment by jsigee87** [comment]
Add more wording and fix spacing here:

![image](https://user-images.githubusercontent.com/22483938/55819715-f9a2e880-5abe-11e9-90fb-1f76439dca33.png)

**Comment by danieldiamont** [comment]
Made help box to clear up issue ssh config issue. Improved the window title bar issue by adding info box with instructions before requesting catkin dir and install dir. Tried to reduce wordiness. Made a TODO for IP config stuff inside of LAN walkthrough.
