### ISSUE TITLE
Somewhere OpenHMDInstallPath is being written as `None`

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#11]
![image](https://user-images.githubusercontent.com/22483938/55818745-f3137180-5abc-11e9-9eca-5a17f07bafe4.png)

**Comment by jsigee87** [comment]
Written to the `~/.bashrc` **

**Comment by jsigee87** [comment]
I am only seeing this on the base. Not sure how it was run to replicate the error. It is written to robot correctly.

**Comment by katebaumli** [comment]
Is this supposed to be closed? @jsigee87

**Comment by jsigee87** [comment]
Its sitting on the bug fixes branch waiting to be tested.

**Comment by jsigee87** [comment]
I havent checked but I think all of the recent commits were on master instead of bug fixes so that branch probably needs to have merge conflicts sorted out now.

**Comment by btandersen383** [comment]
Closed because we dont need to know this, plugin now provides what this points to.

**Comment by btandersen383** [comment]
Link to the commit in a different project that removes this issue from existence in this project.
https://github.com/UTNuclearRoboticsPublic/rviz_openhmd/commit/3e45a2d7b87984c3b4100c1084ff33ef9e933b0e

**Comment by jsigee87** [comment]
Relevant OpenHMD code should be removed from the project before closing.

**Comment by jsigee87** [comment]
Actually, #21  supercedes this, no need for both issues.
