### ISSUE TITLE
UFW firewall prevents subscription to camera topics.

### ISSUE THREAD

**Issue by danieldiamont** [UTNuclearRoboticsPublic/project-crunch#18]
Camera topics are blocked by the firewall.

We can replicate this by enabling UFW with allow port 22 (ssh) and port 11311 (roscore), and run the launcher.

After base_launch.sh and robot_launch.sh both run, we can run 'rostopic list' on the base and see the topics, since this is information transmitted to the base from the roscore on the robot. However, the command 'rosnode ping /cameraX/cameraX_image_view' hangs on the base.

Image from base:
![image](https://user-images.githubusercontent.com/17392378/55835352-94acba00-5ae1-11e9-97a0-ba47749cd46d.png)

To bypass this, I disabled UFW entirely on both computers using 
'sudo ufw disable'.

Result is the following.

![image](https://user-images.githubusercontent.com/17392378/55835269-5c0ce080-5ae1-11e9-87b5-1e354ec29c78.png)

However, this is a temporary workaround. The primary issue right now is that we are whitelisting ports we want to use, e.g. SSH port 22/tcp and ROSCORE port 11311/tcp. However, ROS randomly assigns ports to the camera topics, and we must whitelist these as well. 

A possible solution could be to assign ports in the launch file? Not sure if this is possible.

**Comment by jsigee87** [comment]
I am i thinking for now, we disable the firewall. If possible, lets do this when the LAN is set up? We can leave notes in the readme for whoever is maintaining the code on how to pass in ports to opencv and enable those ports, etc. They can set that up if it fits their use case.

**Comment by jsigee87** [comment]
It is also worth noting that `ufw` is disabled by default... Are we turning it on somewhere unnecessarily?

[https://help.ubuntu.com/community/UFW](https://help.ubuntu.com/community/UFW)

**Comment by danieldiamont** [comment]
![image](https://user-images.githubusercontent.com/17392378/56101242-a4fcd480-5ee7-11e9-901d-caf9790961da.png)

[https://askubuntu.com/questions/22667/why-is-the-firewall-disabled-by-default](url)

Ports ship closed by default. This issue is a bit more complicated. We need to dig in a little bit more about how we open ports without using ufw (frontend for iptables).

My hunch is, we are opening the ports using ufw (the firewall), but then we disable the firewall while the ports remain open. This could be a serious misunderstanding though.

**Comment by jsigee87** [comment]
Commit cc14cd7a84a272f6e0457765f287022aad61577e should fix this, but would like to test before closing.

**Comment by danieldiamont** [comment]
Commit fixed the issue. Closing.
