### ISSUE TITLE
Provide OpenHMD binaries

### ISSUE THREAD

**Issue by btandersen383** [UTNuclearRoboticsPublic/project-crunch#21]
Instead of compiling whole project, we should provide the dynamic binary files with the project. This should remove a whole git clone and compile dependency.

**Comment by btandersen383** [comment]
The rviz_openhmd plugin now provides precompiled binary file and the header needed. We can remove any code relating to cloning and compiling OpenHMD and the environment variables we create for the directory installation. None of it is needed now.

**Comment by btandersen383** [comment]
Since the rviz_openhmd plugin now does not require a separate OpenHMD install, we can completely remove all code relating to installing OpenHMD. That is why # 11 was closed. It was not an issue, it was extraneous code that just needed to be removed. aabeb58 should be enough to close 21. Please double check that all the code relating to OpenHMD install has been removed.

**Comment by danieldiamont** [comment]
This issue looks closed to me. Install works with OpenHMD binaries AFAIK and there is no trace of the extra code that needed to be removed.
