### ISSUE TITLE
Force quitting app doesn't kill background processes

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#24]
When the app launches the window grays out and force quitting doesn't close everything in the background, including remote computer.

**Comment by danieldiamont** [comment]
**Force Quitting:**
ROS processes on the remote computer must be killed by executing `pkill /opt/ros -f` on the remote, either locally or over an SSH connection on the base.

Similarly, on the base, ROS processes are detached from the Python GUI and will not be terminated if the app crashes and/or is closed.

AFAIK there is no way to kill the ROS processes by hitting the 'X' in the GUI and clicking on 'Force Quit'.

**Window Graying out:**
I think this is a separate issue so I will create a new one.

**Comment by jsigee87** [comment]
I dont think theres an issue needed for the window graying. I think this has more to do with all of those exit buttons need to be hooked up to the kill script.

**Comment by danieldiamont** [comment]
Made a separate issue for Window graying, as it grays out while the app is running. I'll edit the title to make that more clear. As far as tying the X to the kill script, you're right. Let's leave that as a TODO.

**Comment by btandersen383** [comment]
If we fix the window gray out #26 , the user should be able to push a kill button that executes the desired kill script. It sounds to me like one needs fixing before the other?

**Comment by jsigee87** [comment]
I agree, ideally the user should be able to do that. We should find out _why_ the window grays out. We may be able to use subprocess differently to avoid the gray out?
