### ISSUE TITLE
.zip Release Does Not Execute

### ISSUE THREAD

**Issue by danieldiamont** [UTNuclearRoboticsPublic/project-crunch#27]
Using the Archive Extractor, the `.zip` version of the release does not execute when the icons for the binaries are clicked. Neither the Installer nor the App.

The `.tar` version appears to run just fine though for both the installer and the app. Thoughts?

I see no difference in the metadata of the executable.

![image](https://user-images.githubusercontent.com/17392378/56085181-a1dce800-5e04-11e9-9d13-cedb3ab5cdf1.png)

**Comment by jsigee87** [comment]
Easy solution here- discontinue the zip.

**Comment by danieldiamont** [comment]
Done. .zip removed from release.

**Comment by jsigee87** [comment]
The release script and documentation needs to be updated, reopening.
