### ISSUE TITLE
Inform user of chosen catkin path on install

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#3]
Pop up a new box in the installer process to let the user know the catkin path they chose and allow them to go back if it is incorrect.

**Comment by jsigee87** [comment]
Pop up box working, however if the user manages to "cheat" and skip the folder selection, we give them a dialog like this:

![image](https://user-images.githubusercontent.com/22483938/55664146-3c2ea180-57ef-11e9-8781-50fb6d11418b.png)

We should check for this and tell the user they selected nothing!

**Comment by jsigee87** [comment]
Also this gets you stuck in an infinite loop if you don't choose.

**Comment by btandersen383** [comment]
I thought I did not cheat and got the same message. I clicked open when prompted for a catkin directory and this is the message I was shown.

**Comment by jsigee87** [comment]
I wonder if we just need `str(self.catkin)`?

**Comment by danieldiamont** [comment]
fixed infinite loop issue and the variable name was incorrect. It works now!
