### ISSUE TITLE
ROBOT_CATKIN_PATH was missing on base `.xsessionrc`

### ISSUE THREAD

**Issue by danieldiamont** [UTNuclearRoboticsPublic/project-crunch#44]
Ensure that this gets written into `.xsessionrc` as well as any other necessary environment variables, e.g., `ROS_IP`.

**Comment by jsigee87** [comment]
This occurs [here](https://github.com/UTNuclearRoboticsPublic/project-crunch/blob/4cf4e2401495189955964f7dc3fb8975ee7bea42/installer/src/main/resources/base/configure_ssh_keys.sh#L107)

`ROBOT_IP` written to `.bashrc` in a1fc60d

@danieldiamont can you take a look. I don't see any reason `ROBOT_CATKIN_PATH` shouldn't have been written.
