### ISSUE TITLE
Position windows error

### ISSUE THREAD

**Issue by amrelazizi** [UTNuclearRoboticsPublic/project-crunch#46]
When running from release, I get an error on line 294 of main.py

IndexError: list index out of range.

This happens after the camera are launched on the remote station when it is trying to position the windows to create the display for the VR headset.

Specifically, this is the line that tries to run split on the output of grep HMD1 from wmctrl -l and access index 0. When I tried to run that manually I got no output from grep, which would explain the index out of bounds.

**Comment by amrelazizi** [comment]
When I run Project-Crunch.run, this is the text that pops up as the error text:

[INFO: robo_launch.sh 110] Cameras found at /dev/video2
/dev/video1
[INFO: robo_launch.sh 126] Two cameras launched from /dev/video2 and /dev/video1
Traceback (most recent call last):
  File "main.py", line 381, in <module>
  File "main.py", line 367, in run
  File "main.py", line 232, in on_done_button_click
  File "main.py", line 271, in launch_system_backend
  File "main.py", line 294, in position_windows
IndexError: list index out of range

When I run xrandr and xrandr | grep 2160x1200 manually it works. When I check ls -al /dev/hidraw* I get:

crw-rw-rw- 1 root plugdev 238, 0 May 29 12:42 /dev/hidraw0
crw------- 1 root root    238, 1 May 28 10:51 /dev/hidraw1
crw-rw-rw- 1 root plugdev 238, 2 May 29 12:42 /dev/hidraw2
crw-rw-rw- 1 root plugdev 238, 3 May 29 12:42 /dev/hidraw3
crw-rw-rw- 1 root plugdev 238, 4 May 29 12:42 /dev/hidraw4
crw-rw-rw- 1 root plugdev 238, 5 May 29 12:42 /dev/hidraw5
crw------- 1 root root    238, 6 May 29 12:34 /dev/hidraw6

wmctrl -l | grep HMD1 is the only one that works. I can assume that is because catkin_make didn't properly execute at some point then?

**Comment by amrelazizi** [comment]
Update: I tried to re-run the installer with this in mind and got the following error:

[INFO: install.sh 239] /home/base/catkin_ws/src/rviz_openhmd/src/resources.cfg Line 3 changed from FileSystem=/home/base/catkin_ws/src/rviz_openhmd/src/resources/ to FileSystem=/home/base/catkin_ws/src/rviz_openhmd/src/resources/
/home/base/Project-Crunch/Install/target/Install/install.sh: line 243: catkin_make: command not found

It seems catkin_make is still not working properly.

Update: I ran rosversion -d and it said unknown so I am reinstalling ros.

**Comment by amrelazizi** [comment]
I completely reinstalled Ros and got the following error from Install.run:

```
Traceback (most recent call last):
  File "/home/base/catkin_ws/src/video_stream_opencv/cfg/VideoStream.cfg", line 3, in <module>
    from dynamic_reconfigure.parameter_generator_catkin import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/__init__.py", line 38, in <module>
    import roslib
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/__init__.py", line 50, in <module>
    from roslib.launcher import load_manifest
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/roslib/launcher.py", line 42, in <module>
    import rospkg
ImportError: No module named 'rospkg'
video_stream_opencv/CMakeFiles/video_stream_opencv_gencfg.dir/build.make:63: recipe for target '/home/base/catkin_ws/devel/include/video_stream_opencv/VideoStreamConfig.h' failed
make[2]: *** [/home/base/catkin_ws/devel/include/video_stream_opencv/VideoStreamConfig.h] Error 1
CMakeFiles/Makefile2:3473: recipe for target 'video_stream_opencv/CMakeFiles/video_stream_opencv_gencfg.dir/all' failed
make[1]: *** [video_stream_opencv/CMakeFiles/video_stream_opencv_gencfg.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/base/catkin_ws/src/video_stream_opencv/src/video_stream.cpp:52:51: fatal error: video_stream_opencv/VideoStreamConfig.h: No such file or directory
compilation terminated.
video_stream_opencv/CMakeFiles/video_stream_opencv.dir/build.make:62: recipe for target 'video_stream_opencv/CMakeFiles/video_stream_opencv.dir/src/video_stream.cpp.o' failed
make[2]: *** [video_stream_opencv/CMakeFiles/video_stream_opencv.dir/src/video_stream.cpp.o] Error 1
CMakeFiles/Makefile2:3542: recipe for target 'video_stream_opencv/CMakeFiles/video_stream_opencv.dir/all' failed
make[1]: *** [video_stream_opencv/CMakeFiles/video_stream_opencv.dir/all] Error 2
[ 64%] Linking CXX shared library /home/base/catkin_ws/devel/lib/librviz_openhmd.so
[ 78%] Built target rviz_openhmd
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j16 -l16" failed
```

**Comment by jsigee87** [comment]
How did you reinstall ROS?
What version did you install?
The error in your most recent comment comes from this:

```
ImportError: No module named 'rospkg'
```

which makes me think you dont have rospkg installed. 

The installer typically installs the full desktop version of ROS Kinetic.

Once you get that sorted out, your `catkin_make` issue is likely from a file that ROS must source before the command `catkin_make` becomes available. If I remember correctly, the `catkin_make` command was removed because of this. The file is sourced post-installation and this shouldn't be an issue (this happens [here](https://github.com/UTNuclearRoboticsPublic/project-crunch/blob/cc78cfccaff9a942ae6c5746d63f4a17ffb9b959/installer/src/main/resources/base/install.sh#L101)) but if you want to keep the `catkin_make` command inside the automated installer, it must be added manually to `install.sh`.

Therefore, the lines above would likely change from this:

```
sudo rosdep init
rosdep update
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
echo "source /opt/ros/kinetic/setup.bash" >> ~/.xsessionrc
# shellcheck disable=SC1090
source ~/.bashrc
```

to this:

```
sudo rosdep init
rosdep update
echo "source /opt/ros/kinetic/setup.bash" >> ~/.bashrc
echo "source /opt/ros/kinetic/setup.bash" >> ~/.xsessionrc
# shellcheck disable=SC1090
source ~/.bashrc
# shellcheck disable=SC1090
source /opt/ros/kinetic/setup.bash
```

I would test all of this in the terminal first, as the `source ~/.bashrc` line should take care of this, but something is clearly not right. You should manually inspect the `~/.bashrc` file and make sure that `setup.bash` was sourced, etc.

**Comment by amrelazizi** [comment]
So a few updates:

I tried some fixes to manually install rospkg and that made the installer run without error but Project-Crunch.run still gave me errors. Additionally, when I tried to update Ubuntu it told me my python install was corrupted so I think I need to address that. This is on the desktop from AHG that y'all used as the base station for reference.

Also, when I run sudo rosdep init I get the following:
base@base:~$ sudo rosdep init
Traceback (most recent call last):
  File "/usr/bin/rosdep", line 3, in <module>
    from rosdep2.main import rosdep_main
ImportError: No module named 'rosdep2'

**Comment by jsigee87** [comment]
I am happy to continue to help but in order to do so you'll have to answer the questions that I ask, and provide some more detail surrounding your errors.

I assume at this point ROS Kinetic is installed and working.

What do you mean "update Ubuntu"? 
What told you the python install was corrupted?
Why are you running `sudo rosdep init`?
What errors does the launcher give?

These issues don't sound like they involve Project Crunch. The ROS installation inside the installer is straightforward and it sounds like the configuration of the Ubuntu installation is getting a little out of hand. If you are unable to debug some of these issues, it may be faster to reinstall Ubuntu 16.04. Keeping track of whats been done to the OS is difficult and can get out of hand very quickly.

**Comment by amrelazizi** [comment]
Ok, I'll go through these step by step:

1) When I ran the Project-Crunch.run it told me that I needed to run do-release-upgrade. When I tried that it told me python install was corrupted. Since we want to stick with 16.04 I won't re-run the update  but I fixed the python issue so that should be fine.

2) I misunderstood that you wanted me to change install.sh so I ran the line "sudo rosdep init" manually (And I did it earlier as part of the ros install). However, when I do it now, I get this:

ERROR: default sources list file already exists:
	/etc/ros/rosdep/sources.list.d/20-default.list
Please delete if you wish to re-initialize

I can still change the install.sh lines if you want me to, but I think what I did since the last update solved the rospkg problem (check part 3)

3) The most recent iteration of the launcher does this:

[EE] unknown message type: 0
[ WARN] [1559158963.966298428]: OGRE EXCEPTION(6:FileNotFoundException): '/home/base/catkin_ws/src/rviz_openhmd/src/resources.cfg' file not found! in ConfigFile::load at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreConfigFile.cpp (line 82)
terminate called after throwing an instance of 'Ogre::FileNotFoundException'
  what():  OGRE EXCEPTION(6:FileNotFoundException): '/home/base/catkin_ws/src/rviz_openhmd/src/resources.cfg' file not found! in ConfigFile::load at /build/ogre-1.9-mqY1wq/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreConfigFile.cpp (line 82)
Traceback (most recent call last):
  File "main.py", line 381, in <module>
  File "main.py", line 367, in run
  File "main.py", line 232, in on_done_button_click
  File "main.py", line 271, in launch_system_backend
  File "main.py", line 294, in position_windows
IndexError: list index out of range
[rviz-1] process has died [pid 23197, exit code -6, cmd /opt/ros/kinetic/lib/rviz/rviz -l -d /home/base/catkin/src/rviz_textured_sphere/rviz_cfg/full_launch.rviz __name:=rviz __log:=/home/base/.ros/log/ec3f86d2-8249-11e9-b1b1-204747e64dd9/rviz-1.log].
log file: /home/base/.ros/log/ec3f86d2-8249-11e9-b1b1-204747e64dd9/rviz-1*.log

When I run the launcher RVIZ now pops up but crashes instantly, and I get this set of errors. The cameras are still booting on the robot computer properly.

**Comment by amrelazizi** [comment]
Update: RVIZ now launches however, the cameras now just pop up two blank dark squares on the remote computer and the rviz sphere is yellow and black.

I found this error in the code:
[EE] Could not open device with index: 0, check device permissions?
failed to open device: Could not open device with index: 0, check device permissions?
Error initializing OpenHMD
[rviz-1] process has died [pid 3787, exit code 1, cmd /opt/ros/kinetic/lib/rviz/rviz -l -d /home/base/catkin_ws/src/rviz_textured_sphere/rviz_cfg/full_launch.rviz __name:=rviz __log:=/home/base/.ros/log/3c78f11e-8250-11e9-8f1e-204747e64dd9/rviz-1.log].
log file: /home/base/.ros/log/3c78f11e-8250-11e9-8f1e-204747e64dd9/rviz-1*.log

**Comment by jsigee87** [comment]
I'll skip the python stuff as thats pretty far out of the scope of this issue. There have been far too many changes made to the Ubuntu and Project Crunch installations to reliably troubleshoot this remotely. As it stands there is no possible way to tell your current system configurations and you will have to iteratively debug these OS issues, which are also unrelated to the issue. I would recommend reinstalling everything from scratch. 

Let's move this to the NRG Slack and myself or @danieldiamont would be happy to attempt to help you debug some of this if you'd like to move forward that way.

If you return to the [original issue](https://github.com/UTNuclearRoboticsPublic/project-crunch/issues/46#issuecomment-497047162) feel free to re-open this.
