### ISSUE TITLE
Fix Install finished dialog

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#7]
Install finished message box needs to be fixed, it currently has to-do tags and is not complete.

**Comment by btandersen383** [comment]
Check out the QMessageBox, I think there are several places where we can use it, like in incorrect_password and install_finished.

**Comment by jsigee87** [comment]
Yes, lets change _at least_ the following to `QMessageBox()`:
```
install_finished()
incorrect_password()
install_info()
catkin_info()
```

Without looking at the code I think there are at least a few more.

edit- there is an example `QMessageBox()` somewhere in the installer's `main.py`.

**Comment by danieldiamont** [comment]
Done. QMessageBox.about and QMessageBox.question used for all of these.
