### ISSUE TITLE
Fix wording on user reboot message 

### ISSUE THREAD

**Issue by jsigee87** [UTNuclearRoboticsPublic/project-crunch#9]
In installer we tell the user to reboot, its not clear if we reboot for them or they do it.

**Comment by danieldiamont** [comment]
Currently, we are not restarting the computer. I'll update the message to say the user must restart the computer before configuring SSH keys.

**Comment by jsigee87** [comment]
Can we also actually take the standard approach- “would you like to restart now, yes or no” and link it to a sudo shutdown.

**Comment by danieldiamont** [comment]
Yes. Give me 5 minutes.
